version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "docutils"  # pinned version for readthedocs.org - https://github.com/influxdata/influxdb-client-python/pull/361
